"""added phone number

Revision ID: 09422e2d2e95
Revises: ee5afe0c380a
Create Date: 2022-09-02 11:13:22.554131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09422e2d2e95'
down_revision = 'ee5afe0c380a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
